version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.7.1
    working_directory: ~/pepys-scraper
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            sudo pip install pipenv
            pipenv install
      - run:
          name: Run tests
          command: pipenv run python -m unittest tests/*
